### PR TITLE
Support base16-bytestring-1.0.0.0

### LINKED ISSUE #4: Fails to build with `base16-bytestring-1.0.0.0`
Hi!

I tried downloading and building this library, but ran into a compile error! I noticed that the cabal file specifies a dependency on `base16-bytestring >= 0.1`, but in `1.0.0.0`, there was a breaking API change. In particular, I ran into this error:

```
src/Control/Monad/Trace/Internal.hs:135:3: error:
    • Couldn't match expected type ‘Either String ByteString’
                  with actual type ‘(ByteString, ByteString)’
    • In the pattern: (bs, trail)
      In a case alternative: (bs, trail) | BS.Char8.null trail -> Just bs
      In the expression:
        case Base16.decode $ BS.Char8.pack $ T.unpack t of
          (bs, trail) | BS.Char8.null trail -> Just bs
          _ -> Nothing
    |
135 |   (bs, trail) | BS.null trail -> Just bs
    |   ^^^^^^^^^^^
```

I would love to help out making a patch to fix this, but I'm not sure what the preferred solution is. Would it be better to make a patch that restricts the version bounds to `>= 0.1 && < 1.0.0.0`, or would it be better to make a patch that lets the project compile against `base16-bytestring 1.0.0.0`?

### PR DESCRIPTION
**Pull request by akshaymankar**
Fixes #4

### CODE REVIEW

**Comment by mtth** [comment]
Thanks for the PR @akshaymankar. I've just fixed the issue in https://github.com/mtth/tracing/commit/47a15f08c0d4b82cfb665cdbda4866e1341eea0f; it seemed preferable to avoid using packages that aren't in Stackage's LTS.

**Comment by alaendle** [comment]
@mtth - since base16-bytestring >= 1.0.0.0 is now available (and required) by stackage nightly maybe this change can be applied (and the package reenabled on stackage)?

**Comment by mtth** [comment]
@alaendle - SGTM, I'll try to update it this weekend.

FTR: https://github.com/commercialhaskell/stackage/issues/5649

**Comment by alaendle** [comment]
@mtth But also enjoy the Easter holidays! 🐇

**Comment by mtth** [comment]
`0.0.6.2` now available on Hackage uses the updated `base16-bytestring`.

**Comment by alaendle** [comment]
Time to re-enable it on stackage master and maybe also lts18 (https://github.com/commercialhaskell/stackage/blob/a4e9060dfd73253517af54ee3eb14ac7421ca0cc/build-constraints.yaml#L156)? I would have created a corresponding PR myself, but as far as I understand this something that should be reserved for package maintainers.
